- name: restart prometheus
  docker_container:
    name: prometheus
    state: started
    restart: true

- name: restart grafana
  docker_container:
    name: grafana
    state: started
    restart: true
