- name: restart prometheus
  docker_container:
    name: prometheus
    state: started
    restart: true

- name: restart grafana
  docker_container:
    name: grafana
    state: started
    restart: true

- name: Restart-Docker-Compose
  ansible.builtin.shell:
    cmd: |
      docker compose down
      docker compose up -d
    chdir: "{{ docker_project_dir }}"