---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# MySQL Backup CronJob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-backup
            image: mysql:8.0
            command:
            - /bin/bash
            - -c
            - |
              BACKUP_FILE="backup_$(date +%Y%m%d_%H%M%S).sql"
              echo "Creating MySQL backup: $BACKUP_FILE"
              
              mysqldump \
                -u ${DB_USER} \
                -p${DB_PASSWORD} \
                --single-transaction \
                --all-databases > /backup/$BACKUP_FILE
              
              echo "Backup saved to: /backup/$BACKUP_FILE"
              echo "Backup size: $(du -h /backup/$BACKUP_FILE)"
              
              # Clean up old backups (keep last 7 days)
              find /backup -name "backup_*.sql" -mtime +7 -delete
              echo "Old backups cleaned up"
            
            env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: mysql-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: mysql-root-password
            
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: mysql-backup-pvc
          
          restartPolicy: OnFailure
