- name: Wait for Elasticsearch to be ready
  block:
    - name: Trying with uri module
      uri:
        url: "http://localhost:9209/_cluster/health"
        method: GET
        status_code: 200
        timeout: 30
      register: elasticsearch_health
      retries: 30
      delay: 10
      until: elasticsearch_health.status == 200

- name: Create ILM Policy
  uri:
    url: "{{ elasticsearch_url }}/_ilm/policy/{{ ilm_policy_name }}"
    method: PUT
    body_format: json
    body: "{{ lookup('template', 'ilm-policy.json.j2') }}"
    status_code: 200
  register: ilm_creation

- name: Create Index Templates
  uri:
    url: "{{ elasticsearch_url }}/_index_template/logs-{{ item.name }}-template"
    method: PUT
    body_format: json
    body: "{{ lookup('template', item.name + '-template.json.j2') }}"
    status_code: 200
  loop: "{{ log_types }}"
  register: template_creation