- name: Install Docker 
  hosts: all
  become: True
  roles:
    - ../roles/install-docker

- name: Install Observability stack (observer)
  hosts: observer
  tags:
    - monitoring
    - observer
  roles:
    - ../roles/observer