- name: Make project directories
  hosts: all
  become: True
  tasks:
    - name: Create directories for Elastic project
      ansible.builtin.include_role:
        name: manage-elk
        tasks_from: mkdir.yml

- name: Deploying Elastic cluster
  hosts: all
  become: True
  roles:
    - install-docker
    - manage-elk
    - setup-datastream
