{
 "title": "MySQL Replication (Overview)",
 "tags": [
  "MySQL",
  "replication"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(mysql_up, job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mysql_up{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Slave I/O running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slave SQL running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication Error No",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "mysql_slave_status_last_errno", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Read Only",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}